menu:
  - {name: 'Home', url: '/'}
  - {name: 'Hardware', url: '/hardware'}
  - {name: 'Software', url: '/software'}
  - {name: 'Chrome Extension', url: '/extension'}
  - {name: 'Support', url: '/support'}
  - {name: 'GitHub', url: '/github'}

social:
  - {icon: 'github', link: 'https://github.com/callontv'}
  - {icon: 'twitter', link: 'https://twitter.com/callontv'}
  - {icon: 'instagram', link: 'https://instagram.com/callontv_com'}
  - {icon: 'linkedin', link: 'https://linkedin.com/in/callontv'}
